#!/usr/bin/env bash
#
# Applies the real migrations to a throwaway Postgres and runs the regression
# suite against them.
#
# Deliberately not `supabase start`: this only needs Docker, so it stays runnable
# on any machine and in CI. The trade-off is that auth and storage are stubs
# (tests/00_bootstrap.sql) rather than the real services — good enough for
# constraints, RLS and the ordering functions, which is what the suite covers.
#
# Also rewrites the frontend's constraint inventory
# (mapsy-frontend/src/shared/config/dbConstraints.generated.ts). The file is
# written on every run but only *changes* when the schema did, and a change is a
# failure — so a passing run leaves the working tree exactly as it found it.

set -euo pipefail

CONTAINER="${MAPSY_PG_CONTAINER:-mapsy-pg-test}"
# Matches the major version Supabase provisions for new projects; see
# supabase/.temp/postgres-version after `supabase link`.
IMAGE="${MAPSY_PG_IMAGE:-postgres:17-alpine}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIGRATIONS="$HERE/../migrations"
GENERATED="$HERE/../../mapsy-frontend/src/shared/config/dbConstraints.generated.ts"

if ! docker info >/dev/null 2>&1; then
  echo "Docker 데몬이 꺼져 있음. Docker Desktop을 실행한 뒤 다시 시도." >&2
  exit 1
fi

cleanup() {
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  rm -f "$GENERATED.tmp"
}
trap cleanup EXIT

cleanup
docker run -d --name "$CONTAINER" -e POSTGRES_PASSWORD=test "$IMAGE" >/dev/null

printf 'postgres 기동 대기'
for _ in $(seq 1 60); do
  if docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1; then
    printf ' 준비됨\n'
    break
  fi
  printf '.'
  sleep 1
done
docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 || {
  echo $'\npostgres가 뜨지 않음' >&2
  exit 1
}

apply() {
  docker exec -i "$CONTAINER" psql -U postgres -v ON_ERROR_STOP=1 -q < "$1"
}

apply "$HERE/00_bootstrap.sql"

# Applied in filename order, exactly as `supabase db push` would.
for migration in "$MIGRATIONS"/*.sql; do
  echo "적용: $(basename "$migration")"
  apply "$migration"
done

apply "$HERE/01_grants.sql"
apply "$HERE/02_helpers.sql"

echo
docker exec -i "$CONTAINER" psql -U postgres -v ON_ERROR_STOP=1 \
  < "$HERE/03_wardrobe.sql"

# The frontend maps every constraint name to a Korean message. That map used to
# claim completeness in a comment and drifted three times; now the inventory is
# generated from the schema and a unit test asserts the map covers it.
#
# Written to a temp file and moved into place, never straight to `$GENERATED`.
# A redirect truncates its target before the block runs, so a psql hiccup under
# `set -e` would leave a tracked source file holding an unterminated array
# literal — which breaks typecheck, build and the unit tests at once, with
# nothing pointing at the cause. Same reason `types:gen` goes through a temp file.
#
# NOT NULL is deliberately absent from the list. On Postgres 17 it is not a
# constraint row at all (`pg_attribute.attnotnull`); from 18 it is, as
# `contype = 'n'`, and this filter keeps excluding it — the auto-generated names
# it would bring (`items_title_not_null`) are not sentences to show anyone.
# SQLSTATE 23502 in errorMessage covers that case instead. So "generated list"
# means these four contypes, not "every constraint".
{
  echo "/**"
  echo " * Constraint names in the \`public\` schema."
  echo " *"
  echo " * Generated by supabase/tests/run.sh from the schema the migrations build."
  echo " * Do not edit — run \`pnpm test:db\` to refresh."
  echo " *"
  echo " * \`errorMessage\` must map every name here; errorMessage.test.ts asserts it."
  echo " */"
  echo "export const DB_CONSTRAINTS = ["
  docker exec "$CONTAINER" psql -U postgres -tAq -c \
    "select conname from pg_constraint c
       join pg_namespace n on n.oid = c.connamespace
      where n.nspname = 'public' and c.contype in ('c','u','f','p')
      order by conname;" | sed "s/^/  '/;s/\$/',/"
  echo "] as const"
} > "$GENERATED.tmp"
mv "$GENERATED.tmp" "$GENERATED"

# Re-applying must be a no-op: a migration that fails halfway has to be
# retryable, and that property is easy to break without noticing.
echo
echo "멱등성 확인 — 마이그레이션 재실행"
for migration in "$MIGRATIONS"/*.sql; do
  apply "$migration"
done
echo "재실행 통과"

# Last, so it is the final word rather than a line buried under the NOTICEs
# above — and a failure, not a notice. Warning and exiting 0 left the guarantee
# resting on "remember to run `pnpm test` afterwards": add a constraint, run only
# the cheap suites against a stale inventory, and everything is green while the
# new name has no message. Compared against HEAD rather than the index so an
# already-staged regeneration still counts as a change.
echo

# `git diff` says nothing about a path it is not tracking, so gitignoring the
# generated file would turn the gate below into a silent no-op. The repo already
# ignores one generated tree (styled-system/), which is exactly the precedent
# that would make someone try it here.
if ! git -C "$HERE/.." ls-files --error-unmatch "$GENERATED" >/dev/null 2>&1; then
  echo "생성 파일이 git에 추적되지 않음: $(basename "$GENERATED")" >&2
  echo "추적되지 않으면 아래 드리프트 검사가 조용히 통과함. 커밋 대상에서 빼지 말 것." >&2
  exit 1
fi

if ! git -C "$HERE/.." diff HEAD --quiet -- "$GENERATED"; then
  echo "제약 목록이 갱신됨: $(basename "$GENERATED")" >&2
  echo "errorMessage의 매핑을 맞춘 뒤 생성 파일과 함께 커밋할 것." >&2
  exit 1
fi
echo "제약 목록 최신"
