/**
 * Constraints in the `public` schema — names, and what they check.
 *
 * Generated by supabase/tests/run.sh from the schema the migrations build.
 * Do not edit — run `pnpm test:db` to refresh.
 *
 * `errorMessage` must map every name here; errorMessage.test.ts asserts it.
 * The definitions carry the *values*: the form mirrors several ceilings so a
 * violation is caught before five photos have uploaded, and limits.test.ts
 * asserts each mirror still matches. Names alone did not catch that —
 * `items_price_max` drifted with its name intact.
 */
export const DB_CONSTRAINTS = [
  'item_images_dimensions_positive',
  'item_images_item_fk',
  'item_images_item_sort_key',
  'item_images_path_not_blank',
  'item_images_pkey',
  'item_images_sort_order_range',
  'items_brand_length',
  'items_category_group_valid',
  'items_colors_distinct',
  'items_colors_limit',
  'items_colors_valid',
  'items_fit_length',
  'items_id_user_key',
  'items_memo_length',
  'items_pkey',
  'items_price_max',
  'items_price_non_negative',
  'items_purchase_place_length',
  'items_seasons_distinct',
  'items_seasons_limit',
  'items_seasons_valid',
  'items_size_length',
  'items_status_valid',
  'items_tags_distinct',
  'items_tags_element_length',
  'items_tags_limit',
  'items_title_length',
  'items_title_not_blank',
  'items_user_id_fkey',
] as const

export const DB_CONSTRAINT_DEFS =
{
    "items_pkey": "PRIMARY KEY (id)",
    "items_price_max": "CHECK (((price IS NULL) OR (price <= 1000000000)))",
    "item_images_pkey": "PRIMARY KEY (id)",
    "items_fit_length": "CHECK (((fit IS NULL) OR (length(fit) <= 40)))",
    "items_tags_limit": "CHECK ((cardinality(tags) <= 20))",
    "items_id_user_key": "UNIQUE (id, user_id)",
    "items_memo_length": "CHECK (((memo IS NULL) OR (length(memo) <= 2000)))",
    "items_size_length": "CHECK (((size IS NULL) OR (length(size) <= 40)))",
    "items_brand_length": "CHECK (((brand IS NULL) OR (length(brand) <= 100)))",
    "items_colors_limit": "CHECK ((cardinality(colors) <= 3))",
    "items_colors_valid": "CHECK ((colors <@ ARRAY['black'::text, 'white'::text, 'gray'::text, 'beige'::text, 'brown'::text, 'navy'::text, 'blue'::text, 'sky'::text, 'green'::text, 'khaki'::text, 'yellow'::text, 'orange'::text, 'red'::text, 'pink'::text, 'purple'::text, 'multi'::text]))",
    "items_status_valid": "CHECK ((status = ANY (ARRAY['owned'::text, 'disposed'::text])))",
    "items_title_length": "CHECK ((length(title) <= 100))",
    "items_user_id_fkey": "FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE",
    "item_images_item_fk": "FOREIGN KEY (item_id, user_id) REFERENCES items(id, user_id) ON DELETE CASCADE",
    "items_seasons_limit": "CHECK ((cardinality(seasons) <= 4))",
    "items_seasons_valid": "CHECK ((seasons <@ ARRAY['spring'::text, 'summer'::text, 'fall'::text, 'winter'::text]))",
    "items_tags_distinct": "CHECK (private.has_unique_elements(tags))",
    "items_colors_distinct": "CHECK (private.has_unique_elements(colors))",
    "items_title_not_blank": "CHECK ((length(btrim(title)) > 0))",
    "items_seasons_distinct": "CHECK (private.has_unique_elements(seasons))",
    "items_price_non_negative": "CHECK (((price IS NULL) OR (price >= 0)))",
    "item_images_item_sort_key": "UNIQUE (item_id, sort_order) DEFERRABLE INITIALLY DEFERRED",
    "items_tags_element_length": "CHECK ((private.max_element_length(tags) <= 40))",
    "item_images_path_not_blank": "CHECK (((length(btrim(path)) > 0) AND (length(btrim(thumb_path)) > 0)))",
    "items_category_group_valid": "CHECK (((split_part(category_id, '.'::text, 1) = ANY (ARRAY['top'::text, 'bottom'::text, 'outer'::text, 'onepiece'::text, 'shoes'::text, 'bag'::text, 'accessory'::text, 'etc'::text])) AND (length(split_part(category_id, '.'::text, 2)) > 0)))",
    "items_purchase_place_length": "CHECK (((purchase_place IS NULL) OR (length(purchase_place) <= 100)))",
    "item_images_sort_order_range": "CHECK (((sort_order >= 0) AND (sort_order <= 4)))",
    "item_images_dimensions_positive": "CHECK ((((width IS NULL) OR (width > 0)) AND ((height IS NULL) OR (height > 0))))"
}
