/**
 * Constraint names in the `public` schema.
 *
 * Generated by supabase/tests/run.sh from the schema the migrations build.
 * Do not edit — run `pnpm test:db` to refresh.
 *
 * `errorMessage` must map every name here; errorMessage.test.ts asserts it.
 */
export const DB_CONSTRAINTS = [
  'item_images_dimensions_positive',
  'item_images_item_fk',
  'item_images_item_sort_key',
  'item_images_path_not_blank',
  'item_images_pkey',
  'item_images_sort_order_range',
  'items_brand_length',
  'items_category_group_valid',
  'items_colors_distinct',
  'items_colors_limit',
  'items_colors_valid',
  'items_fit_length',
  'items_id_user_key',
  'items_memo_length',
  'items_pkey',
  'items_price_max',
  'items_price_non_negative',
  'items_purchase_place_length',
  'items_seasons_distinct',
  'items_seasons_limit',
  'items_seasons_valid',
  'items_size_length',
  'items_status_valid',
  'items_tags_distinct',
  'items_tags_element_length',
  'items_tags_limit',
  'items_title_length',
  'items_title_not_blank',
  'items_user_id_fkey',
] as const
